
services:
  app:
    build: .
    image: studymate-auth:1.0
    ports:
      - "${SERVER_PORT:-8080}:8080"
    environment:
        JWT_SECRET: ${JWT_SECRET}
        REDIS_HOST: ${REDIS_HOST}
        REDIS_PORT: ${REDIS_PORT}
        MONGODB_URI: ${MONGODB_URI:-mongodb://mongo:27017/studymate}
        JWT_EXPIRATION: ${JWT_EXPIRATION:-3600000}
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
