server:
  port: 8080

spring:
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://mongo:27017/studymate}
    redis:
      url: ${REDIS_URL}
      timeout: 5000



jwt:
  secret: ${JWT_SECRET:my-super-secret-key-which-is-long}
  expiration: ${JWT_EXPIRATION:3600000}
