spring:
  application:
    name: School Application Portal

#    redis:
#      host: localhost
#      port: 6379
#      database: 1

jwt:
  secret: my-super-secret-key-which-is-long
  expiration: 3600000 # 1 hour

logging:
  level:
    com.portal.studymate: INFO
    com.portal.studymate.auth: INFO
    com.portal.studymate.user: INFO
    com.portal.studymate.common.jwt: DEBUG
    org.springframework.security: WARN
    org.springframework.data: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/studymate.log

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
    info:
      show-details: always
