spring:
  application:
    name: School Application Portal
  data:
    mongodb:
      uri: mongodb+srv://pankaj_unifocus:Qq4M0SEkN6xRHJj8@cluster0.eqazi0r.mongodb.net/studymate?appName=Cluster0
    redis:
      host: localhost
      port: 6379
      database: 1

jwt:
  secret: my-super-secret-key-which-is-long
  expiration: 3600000 # 1 hour

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
    info:
      show-details: always
